-- Dossy World Seed Data
-- Run this after schema.sql

-- Default Settings
INSERT INTO settings (setting_key, setting_value, description) VALUES
('min_buy_amount', '50', 'Minimum buy amount in KES'),
('max_buy_amount', '5000', 'Maximum buy amount in KES'),
('default_vault_cap', '10000', 'Default vault cap for new rounds'),
('default_profit_percentage', '30', 'Default profit percentage for new rounds'),
('min_withdrawal', '100', 'Minimum withdrawal amount'),
('max_withdrawal', '70000', 'Maximum withdrawal amount'),
('withdrawal_fee', '0', 'Withdrawal fee percentage'),
('auto_start_rounds', 'false', 'Automatically start new rounds'),
('round_cooldown_seconds', '30', 'Seconds between rounds'),
('site_name', 'Dossy World', 'Site display name'),
('site_tagline', 'Fill the Vault. Share the Profit.', 'Site tagline'),
('maintenance_mode', 'false', 'Enable maintenance mode');

-- Admin User (password: admin123 - CHANGE IN PRODUCTION)
-- Password hash for 'admin123' using bcrypt
INSERT INTO users (id, username, email, phone, password_hash, balance, is_admin, is_bot, is_banned) VALUES
('admin-001', 'admin', 'admin@dossy.world', '254700000000', '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4EdAoIpLjF7I9Fta', 0.00, TRUE, FALSE, FALSE);

-- Kenyan Bot Names Pool (common Kenyan names)
INSERT INTO bot_names (first_name, last_name) VALUES
('James', 'Mwangi'),
('Mary', 'Wanjiku'),
('John', 'Kamau'),
('Grace', 'Njeri'),
('Peter', 'Ochieng'),
('Faith', 'Akinyi'),
('David', 'Kipchoge'),
('Sarah', 'Chebet'),
('Michael', 'Otieno'),
('Lucy', 'Muthoni'),
('Joseph', 'Karanja'),
('Esther', 'Wambui'),
('Daniel', 'Kipruto'),
('Ann', 'Moraa'),
('Samuel', 'Wekesa'),
('Joyce', 'Adhiambo'),
('Patrick', 'Mutua'),
('Caroline', 'Nyambura'),
('George', 'Omondi'),
('Agnes', 'Kemunto'),
('Brian', 'Kosgei'),
('Mercy', 'Chepkoech'),
('Kevin', 'Muchiri'),
('Beatrice', 'Wangari'),
('Collins', 'Rotich'),
('Winnie', 'Auma'),
('Dennis', 'Ndungu'),
('Sharon', 'Jepkosgei'),
('Felix', 'Musyoka'),
('Nancy', 'Nyawira'),
('Victor', 'Sang'),
('Diana', 'Cheptoo'),
('Stephen', 'Maina'),
('Rose', 'Atieno'),
('Anthony', 'Kigen'),
('Charity', 'Jeruto'),
('Martin', 'Wafula'),
('Gladys', 'Chelimo'),
('Francis', 'Kimani'),
('Irene', 'Jepchirchir'),
('Charles', 'Barasa'),
('Catherine', 'Nekesa'),
('Edward', 'Chesang'),
('Pamela', 'Cheruiyot'),
('Robert', 'Odongo'),
('Janet', 'Chepngetich'),
('William', 'Korir'),
('Elizabeth', 'Jeptoo'),
('Thomas', 'Wasike'),
('Margaret', 'Chepkemoi'),
('Richard', 'Lagat'),
('Dorothy', 'Jepkirui'),
('Paul', 'Simiyu'),
('Eunice', 'Chepngeno'),
('Timothy', 'Wanyonyi'),
('Christine', 'Jepkogei'),
('Andrew', 'Biwott'),
('Alice', 'Chepchumba'),
('Mark', 'Kibet'),
('Susan', 'Jepkurui'),
('Simon', 'Chesire'),
('Peninah', 'Chepyator'),
('Emmanuel', 'Mutai'),
('Rachael', 'Jepwambok'),
('Oscar', 'Tanui'),
('Naomi', 'Chepkwony'),
('Vincent', 'Kipsang'),
('Purity', 'Jepkesho'),
('Nicholas', 'Kiprono'),
('Lilian', 'Chepng''eno'),
('Raymond', 'Kiplagat'),
('Dorcas', 'Jepchoge'),
('Henry', 'Kimeli'),
('Milka', 'Cheptarus'),
('Kelvin', 'Kiptanui'),
('Evelyn', 'Jepketer'),
('Stanley', 'Cheruiyot'),
('Jacqueline', 'Chepkirui'),
('Leonard', 'Kiprop'),
('Hellen', 'Jepkosgei'),
('Geoffrey', 'Kipsiele'),
('Consolata', 'Chepkesis'),
('Bernard', 'Kipkorir'),
('Teresa', 'Jepterek'),
('Douglas', 'Kimutai'),
('Monicah', 'Chepchai'),
('Alex', 'Kipkogei'),
('Anastasia', 'Jepsiele'),
('Ronald', 'Kipsoi'),
('Veronica', 'Chepkiror');
